# Site settings
title: Seungjae Lee
email: sj98lee@kaist.ac.kr
description: > # this means to ignore newlines until "baseurl:"
  To study ROS, SLAM, ML, PyTroch, Optimization, ...
baseurl: ""
url: "https://seungjae24.github.io"
theme-path: theme-assets # path to header assets etc
map-api-key: AIzaSyB3U7uwIvCyq01orxppAIC1v73y-FBGygY
sass:
  sass_dir: _sass
  style: compressed

collections:
  case:
    output: true
    permalink: /case-studies/:path/
  resource:
    output: true
    permalink: /resources/:path/

# Build settings
markdown: kramdown